#!/bin/sh

if [ ! -d server_modules ]; then
    mkdir -p server_modules/lib/luarocks/rocks-5.4
fi

if [ "$1" = "make" ]; then
    luarocks --lua-version=5.1 --project-tree="$(pwd)/server_modules" make server-dev-1.rockspec
else
    luarocks --lua-version=5.1 --project-tree="$(pwd)/server_modules" "$@"
fi
